---
version: "3.8"

services:
  db:
    container_name: codebattles-october-2022-api-db
    image: "postgres:14.5"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    restart: always

  app:
    container_name: codebattles-october-2022-api-app
    build: .
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/code/

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
