# Generated by Django 4.1.2 on 2022-10-11 05:06

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("logo", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Advocate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("join_date", models.DateField(default=datetime.datetime.now)),
                ("short_bio", models.TextField(blank=True, null=True)),
                ("long_bio", models.TextField(blank=True, null=True)),
                ("profile_pic", models.TextField(blank=True, null=True)),
                ("youtube_username", models.TextField(blank=True, null=True)),
                ("twitter_username", models.TextField(blank=True, null=True)),
                ("github_username", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.company",
                    ),
                ),
            ],
        ),
    ]
