# Generated by Django 4.1.2 on 2022-10-11 06:50

import random

from django.db import migrations

from tests.test_api.factories import AdvocateFactory, CompanyFactory


def generate_data(apps, schema_editor):
    """Generate data."""
    agora = CompanyFactory(
        name="Agora",
        summary="The Real-Time Engagement (RTE) platform to help developers embed voice/video chat, interactive streaming and messaging.",
    )
    AdvocateFactory(
        company=agora,
        name="Dennis Ivy",
        youtube_username="UCTZRcDjjkVajGL6wd76UnGg",
        github_username="divanov11",
        twitter_username="dennisivy11",
    )
    for _ in range(20):
        AdvocateFactory(company=agora)
    for _ in range(100):
        company = CompanyFactory()
        for _ in range(random.randint(10, 50)):
            AdvocateFactory(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(generate_data, migrations.RunPython.noop)
    ]
