# Generated by Django 4.1.2 on 2022-10-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20221011_0650"),
    ]

    operations = []
