# Generated by Django 4.1.2 on 2022-10-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20221011_0650"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advocate",
            options={"ordering": ["-name"]},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["-name"],
                "verbose_name_plural": "Companies",
            },
        ),
    ]
